[package]
name = "wavers"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
criterion = "0.4.0"
memmap2 = "0.5.10"
ndarray = "0.15.6"
pyo3 = "0.18.1"

[profile.release]
debug = true
panic = "abort"

[profile.profiling]
inherits = "release"
