[package]
name = "wavers"
version = "0.1.1"
edition = "2021"
authors = ["Jack Geraghty (jmg049)"]
description = "A Rust crate for reading and writing WAVE files."
readme = "./README.md"
exclude = ["resources/*", "tmp_scripts/*", "benches/massif*"]
license = "MIT"
repository = "https://github.com/jmg049/wavers/"
documentation = "https://docs.rs/wavers/"

[dev-dependencies]
approx_eq = "0.1.8"
criterion = "0.4.0"
uuid = { version = "1.3.0", features = ["v4","fast-rng"] }

[dependencies]
hound = "3.5.0"
itertools = "0.10.5"
num-traits = "0.2.15"
numpy = "0.18.0"
pyo3 = "0.18.1"

[profile.release]
panic = "abort"

[profile.profiling]
inherits = "release"

[[bench]]
name = "benches"
harness = false