[package]
name = "wavers"
version = "1.0.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
paste = "1.0.14"
thiserror = "1.0.48"
ndarray = { version = "0.15.6", optional = true }
pyo3 = { version = "0.19.2", features = ["extension-module"], optional = true }

[dev-dependencies]
approx_eq = "0.1.8"
criterion = "0.5.1"
rand = "0.8.5"
hound = "3.5.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true

[profile.bench]
inherits = "release"
debug = true

[[bench]]
name = "benches"
harness = false

## add features
[features]
ndarray = ["dep:ndarray"]
pyo3 = ["dep:pyo3"]
